### ISSUE TITLE
Create training keys for participants

### ISSUE THREAD

**Issue by sbrunswi** [ironhacks/terraform-key-generation#2]
- [ ] add script about random assignment to repo (if script exists, otherwise matt has to write it) 
- [ ] add links to google documentation about google admin key generation
- [ ] generate 100 training keys valid until November 28th- 50 for damqtV7yE8O5JfMk0WQw and 50 for the kvTuhVvExwQoQ9Oovfld
- [ ] assign keys to participants and put into profile
- [ ] comment in this issue when new keys are available
- [ ] create post in forum once keys are available

**Comment by sbrunswi** [comment]
I think we can close it...

**Comment by charrismatic** [comment]
I will create a new repo with the new scripts that we're using now

**Comment by sbrunswi** [comment]
ok! good. Agreed.
